/*

	       Copyright(c) 2003 by Andrew E. Page

		      All Rights Reserved

Permission to use, copy, modify, and distribute this software and its
documentation for any purpose and without fee is hereby granted,
provided that the above copyright notice appears in all copies and that
both that copyright notice and this permission notice appear in
supporting documentation, and that the name Andrew E. Page not be used
in advertising or publicity pertaining to distribution of the software
without specific, written prior permission.

ANDREW E. PAGE DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
EVENT SHALL ANDREW E. PAGE BE LIABLE FOR ANY SPECIAL, INDIRECT OR
CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.

*/
 
package org.netsnmp.swingui;

/**
 *
 * @author Andrew E. Page<aepage@users.sourceforge.net>
 */
public class snmpget extends javax.swing.JFrame {
    
    /** Creates new form snmpget */
    public snmpget() {
        initComponents();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        snmpgetJPanel1 = new org.netsnmp.swingui.snmpgetJPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        snmpgetJPanel1.setMinimumSize(new java.awt.Dimension(400, 700));
        getContentPane().add(snmpgetJPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        snmpget frm = new snmpget() ;
        
        frm.setSize(400,700) ;
        frm.setTitle("snmpget") ;
        if( args.length >= 1 )
        	frm.setHost(args[0]) ;
        	
        if( args.length >= 2 ) 
        	frm.setCommunity(args[1]) ;
        	
        frm.show();
    }

	/**
	 * Method setCommunity.
	 * @param string
	 */
	public void setCommunity(String string) {
		snmpgetJPanel1.setCommunity(string) ;
	}


	/**
	 * Method setHost.
	 * @param string
	 */
	public void setHost(String string) {
			snmpgetJPanel1.setHost(string) ;
	}

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.netsnmp.swingui.snmpgetJPanel snmpgetJPanel1;
    // End of variables declaration//GEN-END:variables
    
}

/*
 * $Log: snmpget.java,v $
 * Revision 1.3  2003/03/30 23:06:01  aepage
 * removal of unncessary imports
 *
 * Revision 1.2  2003/03/29 00:07:43  aepage
 * new thread architecture, and expanded mib browser features.
 *
 * Revision 1.1  2003/02/09 23:38:01  aepage
 * initial checkin
 *
 */
